# -*- coding: utf-8 -*-
"""Lezione_01.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLmyll8iD751HBNMy5XTgrUyW5dEHfet
"""

message = "Hello, world"

print(message)

result= 1.7 + 1
print(result)

ore = 12
minuti = 60

print("Numero di minuti totale", ore * minuti)

def UnaRigaVuota (arg):
  print()

print ("Prima Riga")
def UnaRigaVuota():
  print("Seconda riga")
UnaRigaVuota()

#Esercizio 1
#Dichiarare una variabile "nome" e assegnargli il tuo nome. Mandare a schermo.
nome = "Francesca"
print(nome)

#Esercizio 2
#Dichiarare una variabile "eta" e assegnargli la tua età. Mandare a schermo.
età = 22
print(età)

#Esercizio 3
#Dichiarare una variabile "pi" e assegnargli il valore di pi greco (3,14159). Mandare a schermo
pi = 3.14159
print(pi)

import math
print(math.pi)

#Esercizio 4
#Creare una variabile "lunghezza" e assegnargli un valore, quindi riassegnare la variabile a 15. Mandare a schermo.
lunghezza = 10
print(lunghezza)
lunghezza = 15
print(lunghezza)

#Creare una variabile "nome_completo" e assegnargli una stringa contenente il tuo nome e cognome. Mandare a schermo
nome_completo = "Francesca Pia Fimiani"
print(nome_completo)

#Creare una variabile "eta_futura" e assegnargli il valore dell'età che avrai tra 10 anni (utilizzando la variabile età già esistente). Mansare a schermo.
eta = 22
eta_futura = 10
print (eta + eta_futura)

#Creare delle variabili "nome", "cognome" ed "anno_di_nascita" ed assegnargli i valori. Mandare a schermo in un unico print. Sovrascrivere tutte le variabili e rimandare a schermo una seconda volta.
nome = "Francesca"
cognome = "Fimiani"
anno_nascita = "2003"
print(nome,  cognome,  anno_nascita)

#Creare una variabile eta_attuale e assegnargli il valore dell'età che hai attualmente, calcolandola in base all'anno corrente. Mandare a schermo eta_attuale
anno = 2025
anno_nascita= 2003
print(anno - anno_nascita)

!echo "# python" >> README.md
!git init
!git add README.md
!git commit -m "first commit"
!git branch -M main
!git remote add origin https://github.com/francesca03-lab/python.git
!git push -u origin main

!git remote add origin https://github.com/francesca03-lab/python.git
!git branch -M main
!git push -u origin main